version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: def
      POSTGRES_PASSWORD: def
      POSTGRES_DB: def
    ports:
      - "5433:5432"

  web:
    build:
      context: ./
    ports:
      - "8089:8000"
    depends_on:
      - db
    environment:
      DEBUG: "False"
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: "def"
      DB_USER: "def"
      DB_PASSWORD: "def"
      DB_HOST: "db"
      DB_PORT: 5432
    volumes:
      - static_volume:/app/staticfiles/

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:

