# Generated by Django 5.1.5 on 2025-01-28 07:45

import app.validators.telephone
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='F.I.Sh')),
                ('phone', models.CharField(max_length=25, validators=[app.validators.telephone.validate_phone_number], verbose_name='Telefon raqam')),
                ('collected_amount', models.IntegerField(verbose_name='Homiylik summasi')),
                ('org_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Tashkilot nomi')),
                ('sponsor_type', models.CharField(choices=[('individual', 'Jismoniy shaxs'), ('legal_entity', 'Yuridik shaxs')], max_length=120, verbose_name='Homiy turi')),
                ('status', models.CharField(choices=[('moderation', 'Moderatsiy'), ('new', 'Yangi'), ('approved', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=120, verbose_name='Holat')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta orqali'), ('bank_transfer', 'Bank oʻtkazmasi'), ('other', 'Boshqa')], max_length=120, null=True, verbose_name='To‘lov turi')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sana')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120, verbose_name='F.I.Sh')),
                ('degree', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('phd', 'Doktorantura')], default='bachelor', max_length=120, verbose_name='Talim turi')),
                ('phone', models.CharField(max_length=25, validators=[app.validators.telephone.validate_phone_number])),
                ('contract_amount', models.IntegerField(verbose_name='Kontrakt summasi')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sana')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Universitet nomi')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sponsored_students', to='app.sponsor', verbose_name='Homiy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sponsored_students', to='app.student', verbose_name='Talaba')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Universitet', to='app.university'),
        ),
    ]
