# Generated by Django 5.1.5 on 2025-01-29 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
    ]
