# Generated by Django 5.1.5 on 2025-01-29 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sponsor_date_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 29), verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='sponsorstudent',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 29), verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 29), verbose_name='Sana'),
        ),
    ]
